# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 017a3ddd984c068e94e821a5f73942c166c1a212c01f0e8c117a8515a9181005d5937caea4e7d541b92b58682247d81f979fa8edd59c27818da51dbbbf8299da

test:
  secret_key_base: b47bce8c222d04c576c55b93e8cb462fdc973c0d144cb6cdeb106912be5d9978372e4d21d845c5dbc8c9a8e8eec13e29aab245108995c5a986c559615e40c606

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
